name: Trigger auto deployment for emp-fe-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ prod ]
    paths:
    - '**'
    - '.github/workflows/emp-fe-ca-AutoDeployTrigger-9c1abfa2-0d08-4396-ac8d-3e338e26074b.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.EMPFECA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: empacr2501.azurecr.io
          registryUsername: ${{ secrets.EMPFECA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EMPFECA_REGISTRY_PASSWORD }}
          containerAppName: emp-fe-ca
          resourceGroup: emp-rg
          imageToBuild: empacr2501.azurecr.io/emp-fe-ca:${{ github.sha }}
          
            

     

